[project]
id = "ambient_sproutz"
name = "ambient_sproutz"
version = "0.0.1"


[components."core::primitives"]
name = "Primitives"
description = "Components that create primitive (in the geometric sense) objects from their attached entities."

[components."core::primitives::tree"]
type = "Empty"
name = "Tree"
description = """
If attached to an entity alongside the other `treee_*` components, the entity will be converted to a tree primitive.
To easily instantiate a default `tree`, consider using the `tree` concept (e.g. `make_tree`)."""
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_seed"]
type = "I32"
name = "Tree trunk seed"
description = "Set the trunk seed of a `tree` for some predictable randomness"
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_trunk_radius"]
type = "F32"
name = "Tree trunk radius"
description = "Set the trunk radius of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_trunk_height"]
type = "F32"
name = "Tree trunk height"
description = "Set the trunk height of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_branch_length"]
type = "F32"
name = "Tree branch length"
description = "Set the branch length of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_branch_angle"]
type = "F32"
name = "Tree branch angle"
description = "Set the branch angle of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_foliage_radius"]
type = "F32"
name = "Tree foliage radius"
description = "Set the foliage radius of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_foliage_density"]
type = "U32"
name = "Tree foliage density"
description = "Set the foliage density of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_trunk_segments"]
type = "U32"
name = "Tree trunk segments"
description = "Set the trunk segments of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_branch_segments"]
type = "U32"
name = "Tree branch segments"
description = "Set the branch segments of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

[components."core::primitives::tree_foliage_segments"]
type = "U32"
name = "Tree foliage segments"
description = "Set the foliage segments of a `tree` entity, spanning XY-plane."
attributes = ["Debuggable", "Networked", "Store"]

# Concepts

[concepts.tree]
name = "Tree"
description = "A procedural Treee, with trunk, branches and foliage"

[concepts.tree.components]
"core::primitives::tree" = {}
"core::primitives::tree_seed" = 1234
"core::primitives::tree_trunk_radius" = 0.1
"core::primitives::tree_trunk_height"= 1.0
"core::primitives::tree_branch_length" = 0.5
"core::primitives::tree_branch_angle" = 30.0
"core::primitives::tree_foliage_radius" = 0.3
"core::primitives::tree_foliage_density" = 1000
"core::primitives::tree_trunk_segments" = 32
"core::primitives::tree_branch_segments" = 16
"core::primitives::tree_foliage_segments" = 8
